# Generated by Django 5.1.7 on 2025-04-07 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_time', models.DateTimeField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('meeting_duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '60 minutes')], default=30)),
                ('booked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=10)),
                ('meeting_id', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=200, null=True)),
                ('booker_uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_appointments', to=settings.AUTH_USER_MODEL)),
                ('receiver_uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_appointments', to=settings.AUTH_USER_MODEL)),
                ('timeslot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coffeechat.availability')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime_UTC', models.DateTimeField()),
                ('end_datetime_UTC', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoogleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('scopes', models.TextField()),
                ('expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('time_slot_duration', models.IntegerField(default=30)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('block_selected_time', models.BooleanField(default=False)),
                ('import_google_calendar', models.BooleanField(default=False)),
                ('google_connected', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
